USE piggydb;

INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('03/09/18','Apapacheo','Laser','Credito 1952','666.66','TRUE','4');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('03/09/18','Mensualidad','Amazon /tablet','Credito 1952','479.12','TRUE','1');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('03/09/18','Mensualidad','Amazon / laptop','Credito 1952','1543.59','TRUE','1');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('04/08/18','Rappi/uber eats','Sushi','Credito 1952','557','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('06/08/18','Rappi/uber eats','Bowl','Credito 1952','145','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('06/08/18','Farmacia','Benavides','Credito 1952','223.5','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('07/08/18','Social','Cruella renta vestidos','Credito 1952','150','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('04/08/18','Social','Cruella renta vestidos','Efectivo','1300','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('09/08/18','transporte','Gasolina','Credito 1952','500','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('13/08/18','Carreer','Tec','Efectivo','10390','TRUE','2');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('13/08/18','Res','Chez celine','Credito 1952','143','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('14/08/18','Rappi/uber eats','----','Credito 1952','145','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('14/08/18','Coffee shop','starbucks','Credito 1952','77','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('14/08/18','transporte','Uber','Credito 1952','273.61','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('18/08/18','Hormiga','Oxxo','credito 1952','36','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('21/08/18','Subsripcion','Pluralsight','credito 1952','614.61','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('09/08/18','Mascota','Vacunas Ricky ','Credito 1942','350','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('23/08/18','Gifts','Adidas plaza fiesta','Credito 1942','699','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('23/08/18','Transporte','Gasolina','Credito 1942','500','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('24/08/18','Home improvment','Steren','Credito 1942','333.98','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('24/08/18','Home improvment','Steren','Credito 1942','145','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('24/08/18','Subsripcion','Spotify','Debito Banorte','99','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('26/08/18','TRansporte','Uber','credito 1952','25','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('24/08/18','restaurante','bowls','credito 1952','225','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('27/08/18','Rappi/uber eats','----','credito 1952','188','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('27/08/18','Gym','Paire Dance studio ','Debito Banorte','1650','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('28/08/18','Subsripcion','digital ocean','credito 1952','98','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('29/08/18','Transporte','Gasolina','Credito 1942','500','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('08/09/18','Social ','Bar Santo Mar','Credito 1942','180','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('02/09/18','Apapacheo','Publiarte','Debito Banorte','391','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('02/09/18','Restaurante','Tacos Mode','Debito Banorte','108','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('02/09/18','Ropa','Arie','Credito 1942','1173','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('02/08/19','Apapacheo','sephora','Credito 1942','480','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('03/09/18','Apapacheo','Laser','Credito 1952','666.66','TRUE','3');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('03/09/18','Restaurante','Hoku','Efectivo','170','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('03/09/18','Transporte','gasolina','Credito 1942','500','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('05/09/18','Papeleria','Office depot','Debito Banorte','80','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('05/09/18','Negocio','Ecoshell','Credito 1952','348','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('07/09/18','Carreer','Tecnologico','Efectivo','10390','TRUE','1');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('01/09/18','Ropa','Pull And Bear','Efectivo','499','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('10/09/18','coffee shop','Starbucks','Credito 1942','39','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('11/09/18','Apapacheo','Los betos salon ','Debito Banorte','1200','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('12/09/18','Restaurante','Nectarworks','Debito Banorte','200','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('12/09/18','Restaurante','Nectarworks','Debito Banorte','130','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('12/09/18','Mascota','Petco','Credito 1942','765.2','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('13/09/18','Restaurante','Peace and love ','Credito 1942','120','FALSE','0');
INSERT INTO gastos (fecha,categoria,concepto,tipo_de_pago,monto,mensualidad,numero_de_meses) VALUES ('13/09/18','Transporte','Gasolina','Credito 1942','500','FALSE','0');

SELECT * FROM gastos;